param(
  [Parameter(Mandatory = $true)]
  [string]$PluginId,
  [Parameter(Mandatory = $true)]
  [string]$Name,
  [string]$Version = "1.0.0",
  [string]$Author = "unknown",
  [string]$Description = "",
  [string]$DllPath = "",
  [string]$OutRoot = "plugins",
  [ValidateSet("manifest", "in_process", "out_of_process")]
  [string]$Mode = "in_process",
  [string[]]$Capabilities = @("memory.provider", "memory.syscall_bridge"),
  [int]$SyscallRead = -1,
  [int]$SyscallWrite = -1,
  [int]$TimeoutMs = 1000,
  [string]$UserCtxHex = "",
  [switch]$Force
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

if ([string]::IsNullOrWhiteSpace($Description)) {
  $Description = "Generated plugin package for $Name"
}
if (-not (Test-Path $OutRoot)) {
  New-Item -ItemType Directory -Path $OutRoot | Out-Null
}
$outRootAbs = (Resolve-Path $OutRoot).Path
$safeName = ($PluginId -replace '[^A-Za-z0-9._-]', '_')
$pkgDir = Join-Path $outRootAbs $safeName
if (Test-Path $pkgDir) {
  if (-not $Force) {
    throw "package directory exists: $pkgDir (use -Force to overwrite)"
  }
  Remove-Item -Recurse -Force $pkgDir
}

$dirs = @(
  $pkgDir,
  (Join-Path $pkgDir "bin/win64"),
  (Join-Path $pkgDir "docs"),
  (Join-Path $pkgDir "schema"),
  (Join-Path $pkgDir "licenses")
)
foreach ($d in $dirs) {
  New-Item -ItemType Directory -Path $d | Out-Null
}

$entryRel = ""
if ($Mode -eq "in_process" -and -not [string]::IsNullOrWhiteSpace($DllPath)) {
  if (-not (Test-Path $DllPath)) {
    throw "dll not found: $DllPath"
  }
  $dllName = Split-Path -Leaf $DllPath
  Copy-Item -Path $DllPath -Destination (Join-Path $pkgDir "bin/win64/$dllName") -Force
  $entryRel = "bin/win64/$dllName"
}

$pluginJson = [ordered]@{
  id = $PluginId
  name = $Name
  version = $Version
  author = $Author
  description = $Description
  mode = $Mode
  priority = 100
  abi = "r3.plugin.v1"
  supported_arch = @("arm64", "arm32")
  capabilities = $Capabilities
  quickstart = "schema/quickstart.json"
  memory_provider = [ordered]@{
    syscall_read = $SyscallRead
    syscall_write = $SyscallWrite
    timeout_ms = [Math]::Max(1, $TimeoutMs)
    user_ctx_hex = $UserCtxHex
  }
}
if (-not [string]::IsNullOrWhiteSpace($entryRel)) {
  $pluginJson.entry = $entryRel
}

$pluginJsonPath = Join-Path $pkgDir "plugin.json"
$pluginJson | ConvertTo-Json -Depth 12 | Set-Content -Path $pluginJsonPath -Encoding UTF8

$quickstart = [ordered]@{
  fields = @(
    [ordered]@{
      id = "policy"
      label = "Policy"
      type = "u32"
      default = "1"
      description = "policy bitmask"
    },
    [ordered]@{
      id = "token"
      label = "Token"
      type = "u64"
      default = "42"
      description = "auth token"
    }
  )
}
$quickPath = Join-Path $pkgDir "schema/quickstart.json"
$quickstart | ConvertTo-Json -Depth 12 | Set-Content -Path $quickPath -Encoding UTF8

$readme = @"
# $Name

This package is generated by `tools/plugin_packager.ps1`.

## Minimal C-style macros

```c
#include "src/plugin_sdk/R3ModuleCompat.h"

static int PluginInit(void) { return 0; }

module_name("$PluginId");
module_version("$Version");
module_author("$Author");
init_module(PluginInit);
```

## Callback/Event model

- Return `R3_MODULE_DISPATCH_PASS` to keep host default flow.
- Return `R3_MODULE_DISPATCH_HANDLED` to override host default flow.
- Return `R3_MODULE_DISPATCH_ERROR` and provide error text for UI.
"@
$readmePath = Join-Path $pkgDir "docs/README.md"
$readme | Set-Content -Path $readmePath -Encoding UTF8

$licensePath = Join-Path $pkgDir "licenses/third_party_licenses.txt"
"List third-party licenses here." | Set-Content -Path $licensePath -Encoding UTF8

Write-Host "Plugin package generated:"
Write-Host "  $pkgDir"
Write-Host "Files:"
Write-Host "  $pluginJsonPath"
Write-Host "  $quickPath"
Write-Host "  $readmePath"
